# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  buildtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: volta-cli/action@v4

      - name: Cache dependenciesuses
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: version check
        run: yarn -v

      - name: Install package
        run: yarn install

      - name: test
        run: yarn test

      # - run: yarn check:all # TODO: style lintで落ちる

      - name: build
        run: yarn build
